#!/usr/bin/env node
"use strict";
const debug = require('debug')('dva:server');
const dva = require('./');

dva.models.sequelize.sync().then(function () {
  const server = dva.app.listen(dva.app.get('port'), function() {
    debug(`Express server listening on port ${server.address().port}`);
  });
});
