#!/usr/bin/env node
"use strict";

var args = require('minimist')(process.argv);
var app = require('express')();

const data = [{
  source: 1,
  target: 2,
  value: 5
}]

app.get('/', (req, res) => {
  res.send()
})

app.listen(args.p || args.port)
